name: 'action-phswap'
description: 'This action is replacing placeholders in files.'
env:
  DUPLETS:
    description: '`placeholder`:`replacement value` duplets. The swapping will be applied to every files provided in the configuration of this action (see below)'
    required: true
    value: '[{PLACEHOLDER-1}]:[{REPLACEMENT-1}] [{PLACEHOLDER-2}]:[{REPLACEMENT-2}] ... [{PLACEHOLDER-N}]:[{REPLACEMENT-N}]'
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
